/* Based on https://hg.libsdl.org/SDL/file/d984274996dd/src/events/scancodes_linux.h */

#ifdef TRON_ENUMS
    #define MAKE_ENUM(x) x,
#endif
#ifdef TRON_ENUM_STRINGS
    #define MAKE_ENUM(x) #x,
#endif

MAKE_ENUM(TRON_KEY_UNKNOWN)
MAKE_ENUM(TRON_KEY_ESCAPE)
MAKE_ENUM(TRON_KEY_1)
MAKE_ENUM(TRON_KEY_2)
MAKE_ENUM(TRON_KEY_3)
MAKE_ENUM(TRON_KEY_4)
MAKE_ENUM(TRON_KEY_5)
MAKE_ENUM(TRON_KEY_6)
MAKE_ENUM(TRON_KEY_7)
MAKE_ENUM(TRON_KEY_8)
MAKE_ENUM(TRON_KEY_9)
MAKE_ENUM(TRON_KEY_0)
MAKE_ENUM(TRON_KEY_MINUS)
MAKE_ENUM(TRON_KEY_EQUALS)
MAKE_ENUM(TRON_KEY_BACKSPACE)
MAKE_ENUM(TRON_KEY_TAB)
MAKE_ENUM(TRON_KEY_Q)
MAKE_ENUM(TRON_KEY_W)
MAKE_ENUM(TRON_KEY_E)
MAKE_ENUM(TRON_KEY_R)
MAKE_ENUM(TRON_KEY_T)
MAKE_ENUM(TRON_KEY_Y)
MAKE_ENUM(TRON_KEY_U)
MAKE_ENUM(TRON_KEY_I)
MAKE_ENUM(TRON_KEY_O)
MAKE_ENUM(TRON_KEY_P)
MAKE_ENUM(TRON_KEY_LEFTBRACKET)
MAKE_ENUM(TRON_KEY_RIGHTBRACKET)
MAKE_ENUM(TRON_KEY_RETURN)
MAKE_ENUM(TRON_KEY_LCTRL)
MAKE_ENUM(TRON_KEY_A)
MAKE_ENUM(TRON_KEY_S)
MAKE_ENUM(TRON_KEY_D)
MAKE_ENUM(TRON_KEY_F)
MAKE_ENUM(TRON_KEY_G)
MAKE_ENUM(TRON_KEY_H)
MAKE_ENUM(TRON_KEY_J)
MAKE_ENUM(TRON_KEY_K)
MAKE_ENUM(TRON_KEY_L)
MAKE_ENUM(TRON_KEY_SEMICOLON)
MAKE_ENUM(TRON_KEY_APOSTROPHE)
MAKE_ENUM(TRON_KEY_GRAVE)
MAKE_ENUM(TRON_KEY_LSHIFT)
MAKE_ENUM(TRON_KEY_BACKSLASH)
MAKE_ENUM(TRON_KEY_Z)
MAKE_ENUM(TRON_KEY_X)
MAKE_ENUM(TRON_KEY_C)
MAKE_ENUM(TRON_KEY_V)
MAKE_ENUM(TRON_KEY_B)
MAKE_ENUM(TRON_KEY_N)
MAKE_ENUM(TRON_KEY_M)
MAKE_ENUM(TRON_KEY_COMMA)
MAKE_ENUM(TRON_KEY_PERIOD)
MAKE_ENUM(TRON_KEY_SLASH)
MAKE_ENUM(TRON_KEY_RSHIFT)
MAKE_ENUM(TRON_KEY_KP_MULTIPLY)
MAKE_ENUM(TRON_KEY_LALT)
MAKE_ENUM(TRON_KEY_SPACE)
MAKE_ENUM(TRON_KEY_CAPSLOCK)
MAKE_ENUM(TRON_KEY_F1)
MAKE_ENUM(TRON_KEY_F2)
MAKE_ENUM(TRON_KEY_F3)
MAKE_ENUM(TRON_KEY_F4)
MAKE_ENUM(TRON_KEY_F5)
MAKE_ENUM(TRON_KEY_F6)
MAKE_ENUM(TRON_KEY_F7)
MAKE_ENUM(TRON_KEY_F8)
MAKE_ENUM(TRON_KEY_F9)
MAKE_ENUM(TRON_KEY_F10)
MAKE_ENUM(TRON_KEY_NUMLOCKCLEAR)
MAKE_ENUM(TRON_KEY_SCROLLLOCK)
MAKE_ENUM(TRON_KEY_KP_7)
MAKE_ENUM(TRON_KEY_KP_8)
MAKE_ENUM(TRON_KEY_KP_9)
MAKE_ENUM(TRON_KEY_KP_MINUS)
MAKE_ENUM(TRON_KEY_KP_4)
MAKE_ENUM(TRON_KEY_KP_5)
MAKE_ENUM(TRON_KEY_KP_6)
MAKE_ENUM(TRON_KEY_KP_PLUS)
MAKE_ENUM(TRON_KEY_KP_1)
MAKE_ENUM(TRON_KEY_KP_2)
MAKE_ENUM(TRON_KEY_KP_3)
MAKE_ENUM(TRON_KEY_KP_0)
MAKE_ENUM(TRON_KEY_KP_PERIOD)
MAKE_ENUM(0)
MAKE_ENUM(TRON_KEY_LANG5) /* KEY_ZENKAKUHANKAKU */
MAKE_ENUM(TRON_KEY_NONUSBACKSLASH) /* KEY_102ND */
MAKE_ENUM(TRON_KEY_F11)
MAKE_ENUM(TRON_KEY_F12)
MAKE_ENUM(TRON_KEY_INTERNATIONAL1) /* KEY_RO */
MAKE_ENUM(TRON_KEY_LANG3) /* KEY_KATAKANA */
MAKE_ENUM(TRON_KEY_LANG4) /* KEY_HIRAGANA */
MAKE_ENUM(TRON_KEY_INTERNATIONAL4) /* KEY_HENKAN */
MAKE_ENUM(TRON_KEY_INTERNATIONAL2) /* KEY_KATAKANAHIRAGANA */
MAKE_ENUM(TRON_KEY_INTERNATIONAL5) /* KEY_MUHENKAN */
MAKE_ENUM(TRON_KEY_INTERNATIONAL5) /* KEY_KPJPCOMMA */
MAKE_ENUM(TRON_KEY_KP_ENTER)
MAKE_ENUM(TRON_KEY_RCTRL)
MAKE_ENUM(TRON_KEY_KP_DIVIDE)
MAKE_ENUM(TRON_KEY_SYSREQ)
MAKE_ENUM(TRON_KEY_RALT)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_LINEFEED */
MAKE_ENUM(TRON_KEY_HOME)
MAKE_ENUM(TRON_KEY_UP)
MAKE_ENUM(TRON_KEY_PAGEUP)
MAKE_ENUM(TRON_KEY_LEFT)
MAKE_ENUM(TRON_KEY_RIGHT)
MAKE_ENUM(TRON_KEY_END)
MAKE_ENUM(TRON_KEY_DOWN)
MAKE_ENUM(TRON_KEY_PAGEDOWN)
MAKE_ENUM(TRON_KEY_INSERT)
MAKE_ENUM(TRON_KEY_DELETE)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_MACRO */
MAKE_ENUM(TRON_KEY_MUTE)
MAKE_ENUM(TRON_KEY_VOLUMEDOWN)
MAKE_ENUM(TRON_KEY_VOLUMEUP)
MAKE_ENUM(TRON_KEY_POWER)
MAKE_ENUM(TRON_KEY_KP_EQUALS)
MAKE_ENUM(TRON_KEY_KP_PLUSMINUS)
MAKE_ENUM(TRON_KEY_PAUSE)
MAKE_ENUM(0)
MAKE_ENUM(TRON_KEY_KP_COMMA)
MAKE_ENUM(TRON_KEY_LANG1) /* KEY_HANGUEL */
MAKE_ENUM(TRON_KEY_LANG2) /* KEY_HANJA */
MAKE_ENUM(TRON_KEY_INTERNATIONAL3) /* KEY_YEN */
MAKE_ENUM(TRON_KEY_LGUI)
MAKE_ENUM(TRON_KEY_RGUI)
MAKE_ENUM(TRON_KEY_APPLICATION) /* KEY_COMPOSE */
MAKE_ENUM(TRON_KEY_STOP)
MAKE_ENUM(TRON_KEY_AGAIN)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PROPS */
MAKE_ENUM(TRON_KEY_UNDO)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_FRONT */
MAKE_ENUM(TRON_KEY_COPY)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_OPEN */
MAKE_ENUM(TRON_KEY_PASTE)
MAKE_ENUM(TRON_KEY_FIND)
MAKE_ENUM(TRON_KEY_CUT)
MAKE_ENUM(TRON_KEY_HELP)
MAKE_ENUM(TRON_KEY_MENU)
MAKE_ENUM(TRON_KEY_CALCULATOR)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SETUP */
MAKE_ENUM(TRON_KEY_SLEEP)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_WAKEUP */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_FILE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SENDFILE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_DELETEFILE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_XFER */
MAKE_ENUM(TRON_KEY_APP1) /* KEY_PROG1 */
MAKE_ENUM(TRON_KEY_APP2) /* KEY_PROG2 */
MAKE_ENUM(TRON_KEY_WWW) /* KEY_WWW */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_MSDOS */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_COFFEE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_DIRECTION */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CYCLEWINDOWS */
MAKE_ENUM(TRON_KEY_MAIL)
MAKE_ENUM(TRON_KEY_AC_BOOKMARKS)
MAKE_ENUM(TRON_KEY_COMPUTER)
MAKE_ENUM(TRON_KEY_AC_BACK)
MAKE_ENUM(TRON_KEY_AC_FORWARD)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CLOSECD */
MAKE_ENUM(TRON_KEY_EJECT) /* KEY_EJECTCD */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_EJECTCLOSECD */
MAKE_ENUM(TRON_KEY_AUDIONEXT) /* KEY_NEXTSONG */
MAKE_ENUM(TRON_KEY_AUDIOPLAY) /* KEY_PLAYPAUSE */
MAKE_ENUM(TRON_KEY_AUDIOPREV) /* KEY_PREVIOUSSONG */
MAKE_ENUM(TRON_KEY_AUDIOSTOP) /* KEY_STOPCD */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_RECORD */
MAKE_ENUM(TRON_KEY_AUDIOREWIND) /* KEY_REWIND */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PHONE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_ISO */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CONFIG */
MAKE_ENUM(TRON_KEY_AC_HOME)
MAKE_ENUM(TRON_KEY_AC_REFRESH)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_EXIT */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_MOVE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_EDIT */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SCROLLUP */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SCROLLDOWN */
MAKE_ENUM(TRON_KEY_KP_LEFTPAREN)
MAKE_ENUM(TRON_KEY_KP_RIGHTPAREN)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_NEW */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_REDO */
MAKE_ENUM(TRON_KEY_F13)
MAKE_ENUM(TRON_KEY_F14)
MAKE_ENUM(TRON_KEY_F15)
MAKE_ENUM(TRON_KEY_F16)
MAKE_ENUM(TRON_KEY_F17)
MAKE_ENUM(TRON_KEY_F18)
MAKE_ENUM(TRON_KEY_F19)
MAKE_ENUM(TRON_KEY_F20)
MAKE_ENUM(TRON_KEY_F21)
MAKE_ENUM(TRON_KEY_F22)
MAKE_ENUM(TRON_KEY_F23)
MAKE_ENUM(TRON_KEY_F24)
MAKE_ENUM(0) 
MAKE_ENUM(0) 
MAKE_ENUM(0) 
MAKE_ENUM(0) 
MAKE_ENUM(0)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PLAYCD */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PAUSECD */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PROG3 */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PROG4 */
MAKE_ENUM(0)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SUSPEND */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CLOSE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PLAY */
MAKE_ENUM(TRON_KEY_AUDIOFASTFORWARD) /* KEY_FASTFORWARD */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_BASSBOOST */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_PRINT */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_HP */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CAMERA */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SOUND */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_QUESTION */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_EMAIL */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CHAT */
MAKE_ENUM(TRON_KEY_AC_SEARCH)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_CONNECT */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_FINANCE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SPORT */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SHOP */
MAKE_ENUM(TRON_KEY_ALTERASE)
MAKE_ENUM(TRON_KEY_CANCEL)
MAKE_ENUM(TRON_KEY_BRIGHTNESSDOWN)
MAKE_ENUM(TRON_KEY_BRIGHTNESSUP)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_MEDIA */
MAKE_ENUM(TRON_KEY_DISPLAYSWITCH) /* KEY_SWITCHVIDEOMODE */
MAKE_ENUM(TRON_KEY_KBDILLUMTOGGLE)
MAKE_ENUM(TRON_KEY_KBDILLUMDOWN)
MAKE_ENUM(TRON_KEY_KBDILLUMUP)
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SEND */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_REPLY */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_FORWARDMAIL */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_SAVE */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_DOCUMENTS */
MAKE_ENUM(TRON_KEY_UNKNOWN) /* KEY_BATTERY */